apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gallery
  labels:
    app: web-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gallery
  template:
    metadata:
      labels:
        app: web-gallery
    spec:
      volumes:
            - name: resources
              emptyDir: {}
      containers:
      - name: gallery-nginx
        image: virtualraven/webgallery-nginx:version-3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: 'ENABLE_GALLERY_STORE'
            value: 'yay'
          - name: 'MASTER_NODE_URL'
            value: 'webgallery-master-service'
          - name: 'CONTENT_MANAGMENT_DROPBOX_API_KEY'
            valueFrom:
               secretKeyRef:
                name: dropbox-credentials
                key: api-token
          - name: 'GALLERY_URL'
            valueFrom:
               secretKeyRef:
                name: website-data
                key: url
        readinessProbe:
          httpGet:
            path: /manifest.yaml
            port: 80
          periodSeconds: 3
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /manifest.yaml
            port: 80
          failureThreshold: 60
          periodSeconds: 10
        volumeMounts:
          - name: resources
            mountPath: /var/www/gallery/resources
      - name: gallery-api
        image: virtualraven/webgallery-api:version-3.0
        imagePullPolicy: Always
        env:
          - name: 'STRIPE_API_TOKEN'
            valueFrom:
               secretKeyRef:
                name: stripe-credentials
                key: api-token
          - name: "RUST_LOG"
            value: "info"
          - name: "DATA_URL"
            value: http://localhost:80
          - name: 'GALLERY_URL'
            valueFrom:
               secretKeyRef:
                name: website-data
                key: url
        readinessProbe:
          httpGet:
            path: /ok
            port: 8080
          periodSeconds: 3
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /update
            port: 8080
          failureThreshold: 60
          periodSeconds: 10


