apiVersion: v1
kind: Service
metadata:
  name: ingress
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 80
     nodePort: 30006
     targetPort: 80
  selector:
    app: web-gallery
